#+TITLE: DM of APP
#+AUTHOR: Nicolas Bouton
#+DATE: April 2021

NOTE: There are certainly many mistake.

* MPI
** Explaination

   I commented a lot on my code. But I let explain my reasoning.

   I decompose the array in each MPI process where each process have at least
   *SIZE_OF_ARRAY / NB_OF_MPI_PROCESS* and the remaining is added to the
   *REMAIN_VALUE* first processes. It is the optimal way to decompose an array.

   Each process will do its *local reduce* and then call *MPI_Reduce* to reduce
   all *local reduce* of MPI processes.

   Therefore, the main process (Process 0) will have the result. I don't do an
   Allreduce because we don't need this. We just need one process to print the
   result. So I decide to use *MPI_Reduce* instead of *MPI_Allreduce*.
   
* pthread
** Explaination

   I think my comment are enough but I will explain my reasonning.

   I decompose the array to reduce in *NB_THREADS* part and for the remain I
   code the optimal way. I added one element for the first *value of remain*
   theads.

   Then all thread do the reduce of the share array but with their part and
   after they will enter in the mutex, one at a time, for update the share
   reduce varaible with their local recude variable. (addition)

   Then the main have the result because is it that create the shared reduce
   variable.
   
** Value
*** Array
    
    | *Reach*         | *Attribute*     | *Variable* |     *Thread 0* |     *Thread 1* |     *Thread 2* |     *Thread 3* | *Main*         |
    |-----------------+-----------------+------------+----------------+----------------+----------------+----------------+----------------|
    | -               |                 | -          | 0x7f4cb0ae1640 | 0x7f4cafadf640 | 0x7f4cb02e0640 | 0x7f4caf2de640 | 0x7f4cb0ae2740 |
    |-----------------+-----------------+------------+----------------+----------------+----------------+----------------+----------------|
    | global          | -               | a          | 0x55c21e39108c | 0x55c21e39108c | 0x55c21e39108c | 0x55c21e39108c | 0x55c21e39108c |
    | global          | __thread        | b          | 0x7f4cb0ae1638 | 0x7f4cafadf638 | 0x7f4cb02e0638 | 0x7f4caf2de638 | 0x7f4cb0ae2738 |
    | local of thread | static          | c          | 0x55c21e391090 | 0x55c21e391090 | 0x55c21e391090 | 0x55c21e391090 | -              |
    | local of thread | -               | d          | 0x7f4cb0ae0e44 | 0x7f4cafadee44 | 0x7f4cb02dfe44 | 0x7f4caf2dde44 | -              |
    | local of thread | static __thread | e          | 0x7f4cb0ae163c | 0x7f4cafadf63c | 0x7f4cb02e063c | 0x7f4caf2de63c | -              |
    |-----------------+-----------------+------------+----------------+----------------+----------------+----------------+----------------|

*** Explaination
**** Variable a

     For the variable *a*, it is declare *global* without attribute, then all
     thread which are created will use the same address of the variable (they
     will don't create another). Typically, the main thread will create the
     variable and each thread created by the main thread will be used this
     variable.

     Thus we have for the variable *a* the same value for all thread, also for
     the main thread (the processus).

**** Variable b

     For the variable *b*, it is declare *global* but with the attribute
     *__thread* which indicate to create another variable for each thread.

     Therefore, we have a different address for each thread, also for the main
     thread (the processus).

**** Variable c

     For the variable *c*, it is declare *locally in the thread function*
     with the attribute *static* which indicate that variable is initialized
     only once by the program.

     Therefore, all thread use the same variable and we have the same address
     for each thread.

**** Variable d

     For the variable *d*, it is declare *locally* in the thread function withou
     attribue.

     Therefore it is local and all thread have different vairable. So all
     address differ.
     
**** Variable e

     For the variable *e*, it is declare *locally in the thread function* but 
     with *two attribute*, *static* and *__thread*. The first indicate that the
     variable is initialized only once and the second indicate that all thread
     have a different variable. So each thread will initialazed once our
     variable.

     Therefore, as each thread have their own variable, all address differ.
